@echo off
chcp 65001 >nul
title BATTAL MUHASEBE - Masaustu Kurulum
setlocal
set "KLASOR=%~dp0"
set "GIRDI=%~1"
echo.
echo  ============================================
echo    BATTAL MUHASEBE - Masaustu Kisayolu
echo  ============================================
echo.
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='SilentlyContinue'; $masa=[Environment]::GetFolderPath('Desktop'); $ara=@('%KLASOR%', $masa, (Join-Path $env:USERPROFILE 'Downloads'), (Join-Path $env:USERPROFILE 'Desktop')); if($env:OneDrive){ $ara += (Join-Path $env:OneDrive 'Downloads'); $ara += (Join-Path $env:OneDrive 'Desktop') }; $ara = $ara | Select-Object -Unique; $adaylar=@(); $girdi='%GIRDI%'; if($girdi -and (Test-Path -LiteralPath $girdi)){ $adaylar += Get-Item -LiteralPath $girdi }; foreach($d in $ara){ if(Test-Path -LiteralPath $d){ $adaylar += (Get-ChildItem -LiteralPath $d -File | Where-Object { $_.Extension -match '^\.html?$' }) } }; $adaylar = $adaylar | Sort-Object FullName -Unique; Write-Host '  Bulunan HTML dosyalari:'; if($adaylar.Count -eq 0){ Write-Host '     (hicbir HTML dosyasi yok)' }; foreach($f in $adaylar){ Write-Host ('     ' + ([math]::Round($f.Length/1MB,2)).ToString().PadLeft(6) + ' MB  ' + $f.FullName) }; Write-Host ''; $panel=$null; foreach($f in ($adaylar | Sort-Object Length -Descending)){ if($f.Length -gt 200000){ $ic=Get-Content -LiteralPath $f.FullName -Raw; if($ic -match 'FIRMA_HESAP_PLANI_INIT'){ $panel=$f; break } } }; if(-not $panel){ Write-Host '  [HATA] Panel HTML dosyasi bulunamadi.' -ForegroundColor Red; Write-Host ''; Write-Host ('  Bu klasorun (' + '%KLASOR%' + ') TUM icerigi:'); $hep=Get-ChildItem -LiteralPath '%KLASOR%' -File; if($hep.Count -eq 0){ Write-Host '     (klasor bos)' }; foreach($x in $hep){ Write-Host ('     ' + ([math]::Round($x.Length/1KB,0)).ToString().PadLeft(8) + ' KB  ' + $x.Name) }; Write-Host ''; Write-Host '  IPUCU: Panel HTML dosyasini bu .bat ile ayni klasore indirin,'; Write-Host '         ya da HTML dosyasini surukleyip bu .bat uzerine birakin.'; exit 1 }; Write-Host ('  Panel bulundu : ' + $panel.FullName) -ForegroundColor Green; $hedef=Join-Path $masa 'BATTAL-BANKA-POS.html'; if($panel.FullName -ne $hedef){ Copy-Item -LiteralPath $panel.FullName -Destination $hedef -Force }; Write-Host ('  Masaustune    : ' + $hedef); $eski=Join-Path $masa 'BATTAL-BANKA-POS-STANDALONE.html'; if(Test-Path -LiteralPath $eski){ Copy-Item -LiteralPath $hedef -Destination $eski -Force; Write-Host '  Eski STANDALONE kopyasi da tazelendi.' }; $ad=[char]::ConvertFromUtf32(0x1F9FE) + ' BATTAL MUHASEBE.lnk'; $lnk=Join-Path $masa $ad; $s=New-Object -ComObject WScript.Shell; $k=$s.CreateShortcut($lnk); $k.TargetPath=$hedef; $k.WorkingDirectory=$masa; $k.Description='Battal Muhasebe - Banka ve POS Merkezi'; $ikon=Join-Path '%KLASOR%' 'OMER-YILMAZ.ico'; if(Test-Path -LiteralPath $ikon){ $k.IconLocation=($ikon + ',0') }; $k.Save(); if(Test-Path -LiteralPath $lnk){ Write-Host ''; Write-Host '  [OK] Masaustunde kisayol hazir: BATTAL MUHASEBE' -ForegroundColor Green } else { Write-Host '  [HATA] Kisayol olusturulamadi.' -ForegroundColor Red }"
echo.
pause
