@echo off
chcp 65001 >nul
title BATTAL MUHASEBE - Kurulum
setlocal
set "KLASOR=%~dp0"
set "GIRDI=%~1"
echo.
echo  ============================================
echo    BATTAL MUHASEBE PANELI - KURULUM
echo  ============================================
echo.
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='SilentlyContinue'; $masa=[Environment]::GetFolderPath('Desktop'); $kokler=@($masa, '%KLASOR%', (Join-Path $env:USERPROFILE 'Downloads'), (Join-Path $env:USERPROFILE 'Documents')); if($env:OneDrive){ $kokler += (Join-Path $env:OneDrive 'Downloads'); $kokler += (Join-Path $env:OneDrive 'Belgeler'); $kokler += (Join-Path $env:OneDrive 'Documents') }; $kokler = $kokler | Select-Object -Unique; $girdi='%GIRDI%'; $bulunan=@(); if($girdi -and (Test-Path -LiteralPath $girdi)){ $bulunan += Get-Item -LiteralPath $girdi }; foreach($d in $kokler){ if(Test-Path -LiteralPath $d){ $bulunan += (Get-ChildItem -LiteralPath $d -Recurse -Depth 3 -File -ErrorAction SilentlyContinue | Where-Object { ($_.Extension -match '^\.html?$') -and (($_.BaseName -replace '[^A-Za-z]','') -match 'BATTALMUHASEBE') }) } }; $bulunan = $bulunan | Sort-Object FullName -Unique | Sort-Object LastWriteTime -Descending; Write-Host '  BATTAL MUHASEBE adini tasiyan tum kopyalar:'; if($bulunan.Count -eq 0){ Write-Host '     (bulunamadi)' -ForegroundColor Red; Write-Host ''; Write-Host '  Bakilan klasorler:'; foreach($d in $kokler){ Write-Host ('     - ' + $d) }; Write-Host ''; Write-Host '  Cozum: dosyayi bu .bat uzerine surukleyip birakin.'; exit 1 }; foreach($f in $bulunan){ Write-Host ('     ' + ([math]::Round($f.Length/1KB,0)).ToString().PadLeft(6) + ' KB   ' + $f.LastWriteTime.ToString('dd.MM.yyyy HH:mm') + '   ' + $f.FullName) }; $sec=$bulunan[0]; Write-Host ''; Write-Host ('  Secilen (en yeni): ' + $sec.Name) -ForegroundColor Green; $kaynak=$sec.DirectoryName; $hedef=Join-Path $masa 'BATTAL-MUHASEBE'; if(-not (Test-Path -LiteralPath $hedef)){ New-Item -ItemType Directory -Path $hedef | Out-Null }; Copy-Item -Path (Join-Path $kaynak '*') -Destination $hedef -Recurse -Force; Write-Host ('  Klasor masaustune kopyalandi: ' + $hedef); Write-Host ''; Write-Host '  Klasordeki paneller:'; $htmls = Get-ChildItem -LiteralPath $hedef -File | Where-Object { $_.Extension -match '^\.html?$' } | Sort-Object Length -Descending; foreach($f in $htmls){ Write-Host ('     ' + ([math]::Round($f.Length/1KB,0)).ToString().PadLeft(6) + ' KB   ' + $f.Name) }; Write-Host ''; $s=New-Object -ComObject WScript.Shell; $anaDosya=Join-Path $hedef $sec.Name; $ad=[char]::ConvertFromUtf32(0x1F9FE) + ' BATTAL MUHASEBE.lnk'; $lnk=Join-Path $masa $ad; $k=$s.CreateShortcut($lnk); $k.TargetPath=$anaDosya; $k.WorkingDirectory=$hedef; $k.Description='Battal Muhasebe - tum paneller'; $k.Save(); if(Test-Path -LiteralPath $lnk){ Write-Host ('  [OK] Kisayol hazir: ' + $ad) -ForegroundColor Green; Write-Host ('       -> ' + $anaDosya) } else { Write-Host '  [HATA] Kisayol olusturulamadi.' -ForegroundColor Red }"
echo.
pause
