@echo off
chcp 65001 >nul
title KOMUT MERKEZI - Kurulum
setlocal
set "KLASOR=%~dp0"
set "GIRDI=%~1"
echo.
echo  ============================================
echo    OMER YILMAZ KOMUT MERKEZI - KURULUM
echo  ============================================
echo.
powershell -NoProfile -ExecutionPolicy Bypass -Command "$ErrorActionPreference='SilentlyContinue'; $masa=[Environment]::GetFolderPath('Desktop'); $kokler=@($masa, '%KLASOR%', (Join-Path $env:USERPROFILE 'Downloads'), (Join-Path $env:USERPROFILE 'Documents')); if($env:OneDrive){ $kokler += (Join-Path $env:OneDrive 'Downloads'); $kokler += (Join-Path $env:OneDrive 'Belgeler'); $kokler += (Join-Path $env:OneDrive 'Documents') }; $girdi='%GIRDI%'; $adaylar=@(); if($girdi -and (Test-Path -LiteralPath $girdi)){ $adaylar += Get-Item -LiteralPath $girdi }; $kokler = $kokler | Select-Object -Unique; foreach($d in $kokler){ if(Test-Path -LiteralPath $d){ $adaylar += (Get-ChildItem -LiteralPath $d -Recurse -Depth 1 -File -ErrorAction SilentlyContinue | Where-Object { $_.Extension -match '^\.html?$' -and $_.Length -gt 1000000 }) } }; $adaylar = $adaylar | Sort-Object FullName -Unique | Sort-Object Length -Descending; $hub=$null; foreach($f in $adaylar){ $ic=Get-Content -LiteralPath $f.FullName -Raw; if(($ic -match 'KGK-FuatHoca-Panel\.html') -and ($ic -match 'MUHASEBE-PANEL\.html')){ $hub=$f; break } }; if(-not $hub){ Write-Host '  [HATA] Komut Merkezi dosyasi bulunamadi.' -ForegroundColor Red; Write-Host '  Bakilan klasorler:'; foreach($d in $kokler){ Write-Host ('     - ' + $d) }; Write-Host ''; Write-Host '  Cozum: OMER-YILMAZ.html dosyasini bu .bat uzerine surukleyip birakin.'; exit 1 }; Write-Host ('  Bulundu  : ' + $hub.FullName); Write-Host ('  Boyut    : ' + ([math]::Round($hub.Length/1MB,2)) + ' MB'); $hedef=Join-Path $masa 'OMER-YILMAZ.html'; if($hub.FullName -ne $hedef){ Copy-Item -LiteralPath $hub.FullName -Destination $hedef -Force }; Write-Host ('  Masaustune: ' + $hedef); $ikonKaynak=Join-Path '%KLASOR%' 'OMER-YILMAZ.ico'; $ikon=Join-Path $masa 'OMER-YILMAZ.ico'; if((Test-Path -LiteralPath $ikonKaynak) -and (-not (Test-Path -LiteralPath $ikon))){ Copy-Item -LiteralPath $ikonKaynak -Destination $ikon -Force }; $s=New-Object -ComObject WScript.Shell; $ad=[char]::ConvertFromUtf32(0x26A1) + ' KOMUT MERKEZI.lnk'; $lnk=Join-Path $masa $ad; $k=$s.CreateShortcut($lnk); $k.TargetPath=$hedef; $k.WorkingDirectory=$masa; $k.Description='Omer Yilmaz Komut Merkezi - 8 panel tek dosyada'; if(Test-Path -LiteralPath $ikon){ $k.IconLocation=($ikon + ',0') }; $k.Save(); Write-Host ''; if(Test-Path -LiteralPath $lnk){ Write-Host ('  [OK] Masaustunde kisayol hazir: ' + $ad) -ForegroundColor Green } else { Write-Host '  [HATA] Kisayol olusturulamadi.' -ForegroundColor Red }; $eski=Join-Path $masa 'OMER YILMAZ.lnk'; if(Test-Path -LiteralPath $eski){ $k2=$s.CreateShortcut($eski); $k2.TargetPath=$hedef; $k2.WorkingDirectory=$masa; if(Test-Path -LiteralPath $ikon){ $k2.IconLocation=($ikon + ',0') }; $k2.Save(); Write-Host '  [OK] Eski (OMER YILMAZ) kisayolu da bu dosyaya yonlendirildi.' }"
echo.
pause
